### ISSUE TITLE
0 target detected using ACR122U

### ISSUE THREAD

**Issue by Cypaubr** [nfc-tools/pam_nfc#1]
I got an error when I try to add my account, I have an ACR122U plugged and functionnal, I tried with PCSC runnin an not and with different Mifare tags, always the same error...

**Comment by Azenet** [comment]
I ran into the same issue and fixed it by editing `nfcauth.c` like this:

``` diff
diff --git a/nfcauth.c b/nfcauth.c
index ca2ba66..1732e0e 100644
--- a/nfcauth.c
+++ b/nfcauth.c
@@ -62,7 +62,7 @@ nfcauth_get_targets (char **targets[])

     nfc_modulation nm = {
         .nmt = NMT_ISO14443A,
-        .nbr = NBR_UNDEFINED
+        .nbr = NBR_106
     };
```

For some reason NBR_UNDEFINED did not work. I picked the "NBR_106" value from `libnfc/utils/nfc-list.c`.

**Comment by Cypaubr** [comment]
Fixed by update
